# try:
#     print(x)
# except:
#     print("An exception occured")

# try:
#     print(x)
# except NameError:
#     print("variable x is not defined")
# except:
#     print("something else went wrong")

# try:
#     print("hello")
# except:
#     print("something went wrong")
# else:
#     print("nothing went wrong")
try:
    print(x)
except:
    print("something went wrong")
finally:
    print("the try except is finished")